#!/usr/bin/env node
/**
 * Composite action step: post a findings summary on the triggering pull request.
 */
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { isAbsolute, resolve } from "node:path";
import { createHash } from "node:crypto";

function appendOutput(name, value) {
  const out = process.env.GITHUB_OUTPUT;
  if (!out) return;
  writeFileSync(out, `${name}=${String(value)}\n`, { flag: "a" });
}

const workspace = process.env.GITHUB_WORKSPACE || process.cwd();
const reportRel = process.env.INPUT_REPORT_PATH || "shtd-report.json";
const reportPath = isAbsolute(reportRel) ? reportRel : resolve(workspace, reportRel);
const prNumber = process.env.PR_NUMBER;
const healPrUrl = (process.env.INPUT_PR_URL || "").trim();
const repo = process.env.GITHUB_REPOSITORY;

if (!prNumber) {
  console.log("No PR number; skipping comment.");
  process.exit(0);
}

if (!existsSync(reportPath)) {
  console.log(`No report at ${reportPath}; skipping comment.`);
  process.exit(0);
}

const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
if (!token) {
  console.log("GITHUB_TOKEN not set; skipping comment.");
  process.exit(0);
}

process.env.GH_TOKEN = token;
process.env.GITHUB_TOKEN = token;

/** @type {any} */
const report = JSON.parse(readFileSync(reportPath, "utf8"));
const findings = report.run?.findings ?? [];
const patches = report.patches ?? [];
const status = report.run?.status ?? "unknown";
const findingCount = report.run?.stats?.findingsTotal ?? findings.length;
const byKind = report.run?.stats?.findingsByKind ?? {};

const marker = "<!-- shtd-summary -->";
const lines = [
  marker,
  "## Self-healing docs summary",
  "",
  `**Status:** \`${status}\` · **Findings:** ${findingCount} · **Patched files:** ${patches.length}`,
  "",
];

if (Object.keys(byKind).length) {
  lines.push("| Kind | Count |", "| --- | ---: |");
  for (const [kind, n] of Object.entries(byKind)) {
    lines.push(`| ${kind} | ${n} |`);
  }
  lines.push("");
}

if (findings.length) {
  lines.push("<details><summary>Findings (up to 30)</summary>", "");
  for (const f of findings.slice(0, 30)) {
    const msg = f.message || f.evidence?.summary || "";
    lines.push(`- **${f.kind}**/\`${f.confidence}\` \`${f.path}\` — ${msg}`);
  }
  if (findings.length > 30) {
    lines.push(`- _…and ${findings.length - 30} more_`);
  }
  lines.push("", "</details>", "");
} else {
  lines.push("_No findings._", "");
}

if (healPrUrl) {
  lines.push(`Heal PR: ${healPrUrl}`, "");
} else if (report.prUrl) {
  lines.push(`Heal PR: ${report.prUrl}`, "");
} else if (report.prSkippedReason) {
  lines.push(`PR note: ${report.prSkippedReason}`, "");
}

lines.push(
  `JSON report path (upload as artifact): \`${reportPath}\``,
  "",
  `_Generated by \`@shtd/action\` · run \`${report.run?.id ?? "n/a"}\`_`,
);

const body = lines.join("\n");
const tmpBody = resolve(workspace, `.shtd-comment-${prNumber}.md`);
writeFileSync(tmpBody, body, "utf8");

let existingId = null;
const list = spawnSync(
  "gh",
  ["api", `repos/${repo}/issues/${prNumber}/comments`, "--paginate"],
  { encoding: "utf8", env: process.env },
);

if (list.status === 0 && list.stdout) {
  try {
    // --paginate may concatenate multiple JSON arrays; handle single array.
    const text = list.stdout.trim();
    const comments = text.startsWith("[")
      ? JSON.parse(text.includes("][") ? `[${text.slice(1, -1).replace(/\]\[/g, ",")}]` : text)
      : [];
    const found = Array.isArray(comments)
      ? comments.find((c) => typeof c.body === "string" && c.body.includes(marker))
      : null;
    if (found?.id) existingId = found.id;
  } catch {
    // fall through to create
  }
}

let result;
if (existingId) {
  result = spawnSync(
    "gh",
    [
      "api",
      "-X",
      "PATCH",
      `repos/${repo}/issues/comments/${existingId}`,
      "--input",
      "-",
    ],
    {
      encoding: "utf8",
      env: process.env,
      input: JSON.stringify({ body }),
    },
  );
} else {
  result = spawnSync("gh", ["pr", "comment", String(prNumber), "--body-file", tmpBody], {
    encoding: "utf8",
    env: process.env,
  });
}

try {
  unlinkSync(tmpBody);
} catch {
  // ignore
}

if (result.stdout) process.stdout.write(result.stdout);
if (result.stderr) process.stderr.write(result.stderr);

if (result.status !== 0) {
  console.error("Failed to post PR comment (non-fatal).");
  process.exit(0);
}

const digest = createHash("sha256").update(body).digest("hex").slice(0, 12);
appendOutput("comment-digest", digest);
console.log(
  existingId
    ? `Updated existing summary comment #${existingId}`
    : `Posted new summary comment on PR #${prNumber}`,
);
